# Generated by Django 2.1.5 on 2022-08-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basicname', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplicatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complicatedname', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True)),
                ('BasicData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.BasicData')),
            ],
        ),
    ]
